// ─── Global CSS ───────────────────────────────────────────────────────────────
export const CSS = `
/* Fully offline: no webfont CDN. The hardened CSP already blocks
   fonts.googleapis.com, so this app runs on local font stacks
   ('Share Tech Mono'→monospace, 'Orbitron'→sans-serif fallbacks). To restore
   the exact display fonts, bundle the .woff2 files locally + add @font-face. */
*{box-sizing:border-box;margin:0;padding:0;}
::-webkit-scrollbar{width:3px;}
::-webkit-scrollbar-track{background:#0a0a0a;}
::-webkit-scrollbar-thumb{background:#00ff9d33;border-radius:2px;}
input[type=range]{-webkit-appearance:none;appearance:none;height:3px;background:#1a1a1a;border-radius:2px;cursor:pointer;width:100%;}
input[type=range]::-webkit-slider-thumb{-webkit-appearance:none;width:12px;height:12px;background:#00ff9d;border-radius:50%;box-shadow:0 0 8px #00ff9d66;}
@keyframes pulse{0%,100%{opacity:1}50%{opacity:0.35}}
@keyframes slideIn{from{opacity:0;transform:translateX(-6px)}to{opacity:1;transform:translateX(0)}}
.logline{animation:slideIn 0.15s ease;}
button:hover{filter:brightness(1.2);}
`;

// ─── Inline styles object ─────────────────────────────────────────────────────
export const S = {
  root:{minHeight:"100vh",background:"#040407",fontFamily:"'Share Tech Mono',monospace",color:"#bbb",position:"relative",overflow:"hidden"},
  scanlines:{position:"fixed",inset:0,background:"repeating-linear-gradient(0deg,transparent,transparent 2px,rgba(0,255,157,0.012) 2px,rgba(0,255,157,0.012) 4px)",pointerEvents:"none",zIndex:9999},
  header:{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"14px 20px",borderBottom:"1px solid #00ff9d1a",background:"linear-gradient(90deg,rgba(0,255,157,0.03) 0%,transparent 100%)"},
  headerBrand:{display:"flex",alignItems:"center",gap:"12px"},
  brandHex:{fontSize:"28px",color:"#00ff9d",lineHeight:1,filter:"drop-shadow(0 0 8px #00ff9d)"},
  brandTitle:{fontFamily:"'Orbitron',sans-serif",fontSize:"20px",fontWeight:900,letterSpacing:"6px",color:"#fff"},
  brandAccent:{color:"#00ff9d"},
  brandSub:{fontSize:"8px",letterSpacing:"3px",color:"#00ff9d44",marginTop:"3px"},
  headerStatus:{textAlign:"right"},
  statusRow:{display:"flex",alignItems:"center",gap:"8px",justifyContent:"flex-end"},
  dot:{width:"8px",height:"8px",borderRadius:"50%",transition:"all 0.3s"},
  statusLabel:{fontSize:"9px",letterSpacing:"3px"},
  versionTag:{fontSize:"8px",color:"#333",letterSpacing:"2px",marginTop:"4px"},
  layout:{display:"grid",gridTemplateColumns:"270px 1fr 240px",gap:"10px",padding:"10px",height:"calc(100vh - 57px)",overflow:"hidden"},
  leftPanel:{display:"flex",flexDirection:"column",gap:"10px",overflowY:"auto"},
  centerPanel:{display:"flex",flexDirection:"column",gap:"8px",minWidth:0,overflow:"hidden"},
  rightPanel:{display:"flex",flexDirection:"column",gap:"10px",overflow:"hidden"},
  card:{background:"rgba(0,255,157,0.018)",border:"1px solid #00ff9d1a",borderRadius:"2px",padding:"14px",position:"relative"},
  cardLabel:{fontSize:"8px",letterSpacing:"3px",color:"#00ff9d55",marginBottom:"12px",paddingBottom:"6px",borderBottom:"1px solid #00ff9d0d"},
  dropzone:{border:"1px dashed #00ff9d33",borderRadius:"2px",padding:"14px",cursor:"pointer",transition:"all 0.2s",minHeight:"90px",display:"flex",alignItems:"center",justifyContent:"center"},
  dropzoneActive:{border:"1px dashed #00ff9d",background:"rgba(0,255,157,0.04)"},
  dropInner:{textAlign:"center"},
  dropHex:{fontSize:"24px",color:"#00ff9d33",marginBottom:"8px"},
  dropTitle:{fontSize:"10px",letterSpacing:"3px",color:"#666",marginBottom:"4px"},
  dropTypes:{fontSize:"8px",color:"#333",letterSpacing:"1px",marginBottom:"4px"},
  dropHint:{fontSize:"8px",color:"#2a2a2a"},
  fileLoaded:{display:"flex",gap:"10px",alignItems:"center"},
  thumb:{width:"52px",height:"52px",objectFit:"cover",border:"1px solid #00ff9d22"},
  pdfIcon:{fontSize:"32px"},
  fileMeta:{flex:1,minWidth:0},
  fileName:{fontSize:"9px",color:"#00ff9d",letterSpacing:"0.5px",wordBreak:"break-all",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"},
  fileStat:{fontSize:"8px",color:"#555",marginTop:"2px"},
  paramGroup:{marginBottom:"12px"},
  paramHead:{fontSize:"8px",letterSpacing:"2px",color:"#666",marginBottom:"6px"},
  pval:{color:"#00ff9d",marginLeft:"6px"},
  btnRow:{display:"flex",gap:"5px"},
  optBtn:{flex:1,padding:"5px 2px",background:"transparent",border:"1px solid #222",color:"#444",fontSize:"9px",letterSpacing:"1px",cursor:"pointer",fontFamily:"'Share Tech Mono',monospace",transition:"all 0.15s"},
  optBtnOn:{border:"1px solid #00ff9d55",color:"#00ff9d",background:"rgba(0,255,157,0.06)"},
  range:{marginTop:"4px"},
  runBtn:{width:"100%",padding:"11px",background:"rgba(0,255,157,0.07)",border:"1px solid #00ff9d55",color:"#00ff9d",fontSize:"10px",letterSpacing:"3px",cursor:"pointer",fontFamily:"'Orbitron',sans-serif",fontWeight:700,transition:"all 0.2s",marginTop:"4px"},
  runBtnOff:{opacity:0.35,cursor:"not-allowed"},
  bmBtn:{background:"rgba(100,200,255,0.07)",borderColor:"#7ec8e355",color:"#7ec8e3",marginTop:"8px",fontSize:"9px"},
  expBtn:{background:"rgba(255,200,100,0.05)",borderColor:"#ffa50033",color:"#ffa500",marginTop:"6px",fontSize:"8px"},
  stageList:{display:"flex",flexDirection:"column",gap:"7px"},
  stageRow:{display:"flex",alignItems:"center",gap:"9px",padding:"7px 8px",border:"1px solid #0d0d0d",borderRadius:"2px",transition:"all 0.2s",position:"relative",overflow:"hidden"},
  stageRowAct:{border:"1px solid #00ff9d33",background:"rgba(0,255,157,0.03)"},
  stageRowDone:{border:"1px solid #00ff9d14"},
  stageIco:{fontSize:"12px",color:"#2a2a2a",width:"16px",textAlign:"center",flexShrink:0},
  stageText:{flex:1},
  stageName:{fontSize:"8px",letterSpacing:"2px",color:"#666"},
  stageDesc:{fontSize:"7px",color:"#333",marginTop:"1px"},
  stageBar:{position:"absolute",bottom:0,left:0,right:0,height:"1px",background:"linear-gradient(90deg,#00ff9d,transparent)",animation:"pulse 1s infinite"},
  tabs:{display:"flex",gap:"4px",alignItems:"center",marginBottom:"0",flexWrap:"wrap"},
  tab:{padding:"6px 10px",background:"transparent",border:"1px solid #1a1a1a",color:"#444",fontSize:"7px",letterSpacing:"2px",cursor:"pointer",fontFamily:"'Share Tech Mono',monospace",transition:"all 0.15s"},
  tabActive:{border:"1px solid #00ff9d44",color:"#00ff9d",background:"rgba(0,255,157,0.05)"},
  dlBtn:{marginLeft:"auto",padding:"6px 12px",background:"rgba(0,255,157,0.08)",border:"1px solid #00ff9d55",color:"#00ff9d",fontSize:"7px",letterSpacing:"2px",cursor:"pointer",fontFamily:"'Share Tech Mono',monospace"},
  dlBtn2:{padding:"10px 20px",background:"rgba(0,255,157,0.08)",border:"1px solid #00ff9d55",color:"#00ff9d",fontSize:"9px",letterSpacing:"2px",cursor:"pointer",fontFamily:"'Share Tech Mono',monospace",marginTop:"12px"},
  dlBtn3:{width:"100%",padding:"9px",background:"rgba(0,255,157,0.08)",border:"1px solid #00ff9d55",color:"#00ff9d",fontSize:"9px",letterSpacing:"2px",cursor:"pointer",fontFamily:"'Share Tech Mono',monospace",marginTop:"8px"},
  cmpLabels:{display:"flex",justifyContent:"space-between",marginBottom:"6px",fontSize:"8px",letterSpacing:"2px",color:"#444"},
  cmpWrap:{position:"relative",overflow:"hidden",cursor:"col-resize",userSelect:"none",border:"1px solid #00ff9d1a",maxHeight:"55vh"},
  cmpImg:{display:"block",width:"100%",height:"auto",maxHeight:"55vh",objectFit:"contain"},
  cmpOver:{position:"absolute",top:0,left:0,overflow:"hidden",height:"100%"},
  cmpDiv:{position:"absolute",top:0,bottom:0,transform:"translateX(-50%)",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",cursor:"col-resize"},
  cmpLine:{position:"absolute",top:0,bottom:0,width:"2px",background:"#00ff9d",boxShadow:"0 0 12px #00ff9d88"},
  cmpHandle:{width:"28px",height:"28px",background:"#00ff9d",color:"#000",display:"flex",alignItems:"center",justifyContent:"center",fontSize:"12px",borderRadius:"50%",position:"relative",zIndex:10,boxShadow:"0 0 16px #00ff9d"},
  cmpHint:{textAlign:"center",fontSize:"7px",color:"#2a2a2a",letterSpacing:"2px",marginTop:"6px"},
  cmpMeta:{display:"flex",alignItems:"center",gap:"8px",marginTop:"10px",flexWrap:"wrap"},
  metaPill:{padding:"3px 8px",background:"rgba(255,255,255,0.03)",border:"1px solid #222",fontSize:"8px",letterSpacing:"1px",color:"#555"},
  metaPillGreen:{border:"1px solid #00ff9d33",color:"#00ff9d"},
  emptyPreview:{minHeight:"300px",display:"flex",alignItems:"center",justifyContent:"center",position:"relative",overflow:"hidden"},
  emptyDots:{position:"absolute",inset:0,display:"grid",gridTemplateColumns:"repeat(10,1fr)",gap:"2px",padding:"10px"},
  emptyMsg:{position:"relative",textAlign:"center"},
  emptyIcon:{fontSize:"32px",color:"#00ff9d22",marginBottom:"12px"},
  emptyText:{fontSize:"10px",letterSpacing:"4px",color:"#333"},
  emptySubtext:{fontSize:"8px",color:"#222",letterSpacing:"1px",marginTop:"6px"},
  docOut:{textAlign:"center",padding:"50px 20px"},
  docOutIco:{fontSize:"52px",marginBottom:"16px"},
  docOutTitle:{fontSize:"11px",letterSpacing:"4px",color:"#00ff9d",marginBottom:"8px"},
  docOutSub:{fontSize:"9px",color:"#555",letterSpacing:"1px"},
  reportGrid:{display:"flex",flexDirection:"column",gap:"12px",overflowY:"auto",maxHeight:"calc(100vh - 200px)"},
  reportBlock:{borderBottom:"1px solid #0d0d0d",paddingBottom:"10px"},
  rbLabel:{fontSize:"7px",letterSpacing:"3px",color:"#00ff9d44",marginBottom:"5px"},
  rbVal:{fontSize:"10px",color:"#999",lineHeight:"1.6"},
  emptyReport:{textAlign:"center",padding:"60px 20px"},
  sourcesList:{display:"flex",flexDirection:"column",gap:"12px",overflowY:"auto",maxHeight:"calc(100vh - 200px)"},
  sourceItem:{border:"1px solid #0d0d0d",padding:"12px",borderRadius:"2px"},
  sourceQuery:{fontSize:"8px",letterSpacing:"2px",color:"#00ff9d66",marginBottom:"6px"},
  sourceSummary:{fontSize:"9px",color:"#888",lineHeight:"1.6",marginBottom:"4px"},
  sourceRel:{fontSize:"9px",color:"#7ec8e3",marginBottom:"4px"},
  sourceUrl:{fontSize:"8px",color:"#444",marginBottom:"2px",wordBreak:"break-all"},
  terminal:{flex:1,overflowY:"auto",display:"flex",flexDirection:"column",gap:"2px",maxHeight:"calc(100vh - 260px)"},
  termWelcome:{fontSize:"8px",color:"#333",marginBottom:"8px",lineHeight:"1.8"},
  termLine:{fontSize:"8px",display:"flex",gap:"6px",lineHeight:"1.7",letterSpacing:"0.3px"},
  termTs:{color:"#2a2a2a",flexShrink:0},
  errBox:{background:"rgba(255,68,68,0.04)",border:"1px solid #ff444422",padding:"12px",borderRadius:"2px"},
  errTitle:{fontSize:"8px",letterSpacing:"2px",color:"#ff4444",marginBottom:"5px"},
  errMsg:{fontSize:"8px",color:"#ff6666",lineHeight:"1.5"},
  successBox:{background:"rgba(0,255,157,0.03)",border:"1px solid #00ff9d22",padding:"12px",borderRadius:"2px"},
  successTitle:{fontSize:"8px",letterSpacing:"2px",color:"#00ff9d",marginBottom:"4px"},
  successMeta:{fontSize:"8px",color:"#555",marginBottom:"4px"},
  clHeader:{marginBottom:"16px",paddingBottom:"12px",borderBottom:"1px solid #00ff9d0d"},
  clTitle:{fontFamily:"'Orbitron',sans-serif",fontSize:"13px",fontWeight:700,letterSpacing:"4px",color:"#fff",marginBottom:"4px"},
  clSub:{fontSize:"8px",color:"#444",letterSpacing:"1px"},
  clList:{display:"flex",flexDirection:"column",gap:"14px",overflowY:"auto",maxHeight:"calc(100vh - 240px)"},
  clEntry:{border:"1px solid #111",borderRadius:"2px",padding:"14px",background:"rgba(255,255,255,0.01)"},
  clEntryCurrent:{border:"1px solid #00ff9d33",background:"rgba(0,255,157,0.025)"},
  clEntryHead:{display:"flex",alignItems:"center",gap:"10px",marginBottom:"12px",flexWrap:"wrap"},
  clBuildNum:{fontFamily:"'Orbitron',sans-serif",fontSize:"9px",fontWeight:700,color:"#333",letterSpacing:"2px"},
  clVersion:{fontFamily:"'Orbitron',sans-serif",fontSize:"11px",fontWeight:900,color:"#00ff9d",letterSpacing:"2px"},
  clEntryLabel:{fontSize:"8px",letterSpacing:"3px",color:"#666",flex:1},
  clBadge:{fontSize:"7px",letterSpacing:"2px",padding:"3px 8px",borderRadius:"1px"},
  clBadgeCurrent:{background:"rgba(0,255,157,0.1)",color:"#00ff9d",border:"1px solid #00ff9d44"},
  clBadgeDeprecated:{background:"rgba(255,100,100,0.06)",color:"#ff6b6b66",border:"1px solid #ff6b6b22"},
  clDate:{fontSize:"7px",color:"#2a2a2a",letterSpacing:"1px"},
  clSection:{marginBottom:"10px"},
  clSectionLabel:{fontSize:"7px",letterSpacing:"3px",color:"#444",marginBottom:"6px"},
  clBug:{display:"flex",gap:"8px",fontSize:"9px",color:"#ff6b6b99",lineHeight:"1.6",marginBottom:"3px"},
  clFix:{display:"flex",gap:"8px",fontSize:"9px",color:"#00ff9d88",lineHeight:"1.6",marginBottom:"3px"},
  clBulletBug:{color:"#ff4444",flexShrink:0,marginTop:"1px"},
  clBulletFix:{color:"#00ff9d",flexShrink:0,marginTop:"1px"},
  // ── Learning suggestion banner ─────────────────────────────────────────────
  suggBox:{background:"rgba(0,255,157,0.035)",border:"1px solid #00ff9d44",borderRadius:"2px",padding:"10px 12px"},
  suggTitle:{fontSize:"7px",letterSpacing:"3px",color:"#00ff9d55",marginBottom:"5px"},
  suggText:{fontSize:"8px",color:"#888",lineHeight:"1.5",marginBottom:"4px"},
  suggParams:{fontSize:"8px",color:"#7ec8e3",marginBottom:"6px",letterSpacing:"0.5px"},
  suggApply:{padding:"5px 10px",background:"rgba(0,255,157,0.1)",border:"1px solid #00ff9d44",color:"#00ff9d",fontSize:"8px",letterSpacing:"2px",cursor:"pointer",fontFamily:"'Share Tech Mono',monospace"},
  // ── Agent ensemble panel ───────────────────────────────────────────────────
  agentGrid:{display:"flex",flexDirection:"column",gap:"4px",marginTop:"8px"},
  agentRow:{display:"flex",alignItems:"center",gap:"8px",padding:"6px 8px",border:"1px solid #1a1a1a",borderRadius:"2px"},
  agentRowBest:{border:"1px solid #00ff9d44",background:"rgba(0,255,157,0.03)"},
  agentName:{fontSize:"8px",letterSpacing:"2px",color:"#00ff9d",width:"76px",flexShrink:0},
  agentDesc:{fontSize:"7px",color:"#444",flex:1,lineHeight:"1.5"},
  agentScore:{fontSize:"9px",color:"#7ec8e3",width:"36px",textAlign:"right",flexShrink:0},
  agentUseBtn:{padding:"3px 8px",background:"transparent",border:"1px solid #333",color:"#555",fontSize:"7px",letterSpacing:"1px",cursor:"pointer",fontFamily:"'Share Tech Mono',monospace",flexShrink:0},
  // ── Learn tab ─────────────────────────────────────────────────────────────
  learnStats:{display:"flex",flexDirection:"column",gap:"6px",padding:"4px 0",marginBottom:"4px"},
  learnRow:{display:"flex",justifyContent:"space-between",fontSize:"8px",color:"#666",letterSpacing:"0.5px",padding:"5px 0",borderBottom:"1px solid #0d0d0d"},
  learnClearBtn:{marginTop:"14px",padding:"7px 14px",background:"rgba(255,68,68,0.05)",border:"1px solid #ff444433",color:"#ff6666",fontSize:"8px",letterSpacing:"2px",cursor:"pointer",fontFamily:"'Share Tech Mono',monospace"},
};
